### ISSUE TITLE
Problems using the component tOpenERPoutput

### ISSUE THREAD

**Issue by mouadrouass** [baumgaro/Odoo-Talend-Component#10]
Hi,
I'm working on a project of migration from sage Line 100 accounting to OpenERP 7 but i have some problems.
I'm trying to insert data using API topenerp conponent but i got this error;

Démarrage du job res_partner_job a 13:22 28/04/2014.
[statistics] connecting to socket on port 3936
[statistics] connected
Exception in component tOpenERPOutput_2
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at org.apache.xmlrpc.parser.XmlRpcResponseParser.addResult(XmlRpcResponseParser.java:55)
    at org.apache.xmlrpc.parser.RecursiveTypeParserImpl.endValueTag(RecursiveTypeParserImpl.java:71)
    at org.apache.xmlrpc.parser.XmlRpcResponseParser.endElement(XmlRpcResponseParser.java:164)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:175)
    at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:145)
    at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:94)
    at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:39)
    at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:53)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:166)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:136)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:125)
    at com.debortoliwines.openerp.api.Session.executeCommand(Session.java:197)
    at com.debortoliwines.openerp.api.OpenERPCommand.createObject(OpenERPCommand.java:157)
    at migrationsage.res_partner_job_0_1.res_partner_job.tDBInput_1Process(res_partner_job.java:1620)
    at migrationsage.res_partner_job_0_1.res_partner_job.runJobInTOS(res_partner_job.java:1926)
    at migrationsage.res_partner_job_0_1.res_partner_job.main(res_partner_job.java:1791)
[statistics] disconnected
Job res_partner_job terminé à 13:22 28/04/2014. [Code sortie=1]

**Comment by MarcAllain** [comment]
Hi,
I encountered the same problem, and did not found any solution...
I've tried even the example given in the package downloaded on this website (06/11/14) : the reading component works, but not the writing one.
I'm working on Talend Open Studio 5.6 and the current Odoo version (Open ERP 8 i think)
Thanks for your help.
Marc

**Comment by MarcAllain** [comment]
I've noticed that you're quite busy right now, so I've been further in my investigations.
I discovered that it works on my professionnal computer but not on my personnal ...
Looking at the Odoo versions ... The same ... Looking at Talend versions, and testing olders/newers ... The same ... Windows 7 versus Windows 8 : unlikely ... The firewall : does't change anything ...
What about the user's rights ? Bingo : it only works with the "Administrator" user !!!
I don't know why the error message speaks about convertion from integer to string, but the problem is with user rights !
